using LeagueOfStats.Domain.Matches.Enums;

namespace LeagueOfStats.Application.Extensions;

public static class CamilleQueueExtensions
{
    public static Queue ToQueue(this Camille.Enums.Queue queue) =>
        queue switch
        {
            Camille.Enums.Queue.CUSTOM => Queue.Custom,
            Camille.Enums.Queue.SUMMONERS_RIFT_5V5_BLIND_PICK_DEPRECATED_2 => Queue.SummonersRift5V5BlindPickDeprecated2,
            Camille.Enums.Queue.SUMMONERS_RIFT_5V5_RANKED_SOLO_DEPRECATED_4 => Queue.SummonersRift5V5RankedSoloDeprecated4,
            Camille.Enums.Queue.SUMMONERS_RIFT_5V5_RANKED_PREMADE => Queue.SummonersRift5V5RankedPremade,
            Camille.Enums.Queue.SUMMONERS_RIFT_CO_OP_VS_AI => Queue.SummonersRiftCoOpVsAi,
            Camille.Enums.Queue.TWISTED_TREELINE_3V3_NORMAL => Queue.TwistedTreeline3V3Normal,
            Camille.Enums.Queue.TWISTED_TREELINE_3V3_RANKED_FLEX_DEPRECATED_9 => Queue.TwistedTreeline3V3RankedFlexDeprecated9,
            Camille.Enums.Queue.SUMMONERS_RIFT_5V5_DRAFT_PICK_DEPRECATED_14 => Queue.SummonersRift5V5DraftPickDeprecated14,
            Camille.Enums.Queue.CRYSTAL_SCAR_5V5_DOMINION_BLIND_PICK => Queue.CrystalScar5V5DominionBlindPick,
            Camille.Enums.Queue.CRYSTAL_SCAR_5V5_DOMINION_DRAFT_PICK => Queue.CrystalScar5V5DominionDraftPick,
            Camille.Enums.Queue.CRYSTAL_SCAR_DOMINION_CO_OP_VS_AI => Queue.CrystalScarDominionCoOpVsAi,
            Camille.Enums.Queue.SUMMONERS_RIFT_CO_OP_VS_AI_INTRO_BOT_DEPRECATED_31 => Queue.SummonersRiftCoOpVsAiIntroBotDeprecated31,
            Camille.Enums.Queue.SUMMONERS_RIFT_CO_OP_VS_AI_BEGINNER_BOT_DEPRECATED_32 => Queue.SummonersRiftCoOpVsAiBeginnerBotDeprecated32,
            Camille.Enums.Queue.SUMMONERS_RIFT_CO_OP_VS_AI_INTERMEDIATE_BOT_DEPRECATED_33 => Queue.SummonersRiftCoOpVsAiIntermediateBotDeprecated33,
            Camille.Enums.Queue.TWISTED_TREELINE_3V3_RANKED_TEAM => Queue.TwistedTreeline3V3RankedTeam,
            Camille.Enums.Queue.SUMMONERS_RIFT_5V5_RANKED_TEAM => Queue.SummonersRift5V5RankedTeam,
            Camille.Enums.Queue.TWISTED_TREELINE_CO_OP_VS_AI => Queue.TwistedTreelineCoOpVsAi,
            Camille.Enums.Queue.SUMMONERS_RIFT_5V5_TEAM_BUILDER => Queue.SummonersRift5V5TeamBuilder,
            Camille.Enums.Queue.HOWLING_ABYSS_5V5_ARAM_DEPRECATED_65 => Queue.HowlingAbyss5V5AramDeprecated65,
            Camille.Enums.Queue.HOWLING_ABYSS_ARAM_CO_OP_VS_AI => Queue.HowlingAbyssAramCoOpVsAi,
            Camille.Enums.Queue.SUMMONERS_RIFT_ONE_FOR_ALL_DEPRECATED_70 => Queue.SummonersRiftOneForAllDeprecated70,
            Camille.Enums.Queue.HOWLING_ABYSS_1V1_SNOWDOWN_SHOWDOWN => Queue.HowlingAbyss1V1SnowdownShowdown,
            Camille.Enums.Queue.HOWLING_ABYSS_2V2_SNOWDOWN_SHOWDOWN => Queue.HowlingAbyss2V2SnowdownShowdown,
            Camille.Enums.Queue.SUMMONERS_RIFT_6V6_HEXAKILL => Queue.SummonersRift6V6Hexakill,
            Camille.Enums.Queue.SUMMONERS_RIFT_ULTRA_RAPID_FIRE => Queue.SummonersRiftUltraRapidFire,
            Camille.Enums.Queue.HOWLING_ABYSS_ONE_FOR_ALL_MIRROR_MODE => Queue.HowlingAbyssOneForAllMirrorMode,
            Camille.Enums.Queue.SUMMONERS_RIFT_CO_OP_VS_AI_ULTRA_RAPID_FIRE => Queue.SummonersRiftCoOpVsAiUltraRapidFire,
            Camille.Enums.Queue.SUMMONERS_RIFT_DOOM_BOTS_RANK_1 => Queue.SummonersRiftDoomBotsRank1,
            Camille.Enums.Queue.SUMMONERS_RIFT_DOOM_BOTS_RANK_2 => Queue.SummonersRiftDoomBotsRank2,
            Camille.Enums.Queue.SUMMONERS_RIFT_DOOM_BOTS_RANK_5 => Queue.SummonersRiftDoomBotsRank5,
            Camille.Enums.Queue.CRYSTAL_SCAR_ASCENSION_DEPRECATED_96 => Queue.CrystalScarAscensionDeprecated96,
            Camille.Enums.Queue.TWISTED_TREELINE_6V6_HEXAKILL => Queue.TwistedTreeline6V6Hexakill,
            Camille.Enums.Queue.BUTCHERS_BRIDGE_5V5_ARAM => Queue.ButchersBridge5V5Aram,
            Camille.Enums.Queue.HOWLING_ABYSS_LEGEND_OF_THE_PORO_KING_DEPRECATED_300 => Queue.HowlingAbyssLegendOfThePoroKingDeprecated300,
            Camille.Enums.Queue.SUMMONERS_RIFT_NEMESIS => Queue.SummonersRiftNemesis,
            Camille.Enums.Queue.SUMMONERS_RIFT_BLACK_MARKET_BRAWLERS => Queue.SummonersRiftBlackMarketBrawlers,
            Camille.Enums.Queue.SUMMONERS_RIFT_NEXUS_SIEGE_DEPRECATED_315 => Queue.SummonersRiftNexusSiegeDeprecated315,
            Camille.Enums.Queue.CRYSTAL_SCAR_DEFINITELY_NOT_DOMINION => Queue.CrystalScarDefinitelyNotDominion,
            Camille.Enums.Queue.SUMMONERS_RIFT_ARURF_DEPRECATED_318 => Queue.SummonersRiftArurfDeprecated318,
            Camille.Enums.Queue.SUMMONERS_RIFT_ALL_RANDOM => Queue.SummonersRiftAllRandom,
            Camille.Enums.Queue.SUMMONERS_RIFT_5V5_DRAFT_PICK => Queue.SummonersRift5V5DraftPick,
            Camille.Enums.Queue.SUMMONERS_RIFT_5V5_RANKED_DYNAMIC => Queue.SummonersRift5V5RankedDynamic,
            Camille.Enums.Queue.SUMMONERS_RIFT_5V5_RANKED_SOLO => Queue.SummonersRift5V5RankedSolo,
            Camille.Enums.Queue.SUMMONERS_RIFT_5V5_BLIND_PICK => Queue.SummonersRift5V5BlindPick,
            Camille.Enums.Queue.SUMMONERS_RIFT_5V5_RANKED_FLEX => Queue.SummonersRift5V5RankedFlex,
            Camille.Enums.Queue.HOWLING_ABYSS_5V5_ARAM => Queue.HowlingAbyss5V5Aram,
            Camille.Enums.Queue.TWISTED_TREELINE_3V3_BLIND_PICK => Queue.TwistedTreeline3V3BlindPick,
            Camille.Enums.Queue.TWISTED_TREELINE_3V3_RANKED_FLEX_DEPRECATED_470 => Queue.TwistedTreeline3V3RankedFlexDeprecated470,
            Camille.Enums.Queue.SUMMONERS_RIFT_BLOOD_HUNT_ASSASSIN => Queue.SummonersRiftBloodHuntAssassin,
            Camille.Enums.Queue.COSMIC_RUINS_DARK_STAR_SINGULARITY => Queue.CosmicRuinsDarkStarSingularity,
            Camille.Enums.Queue.SUMMONERS_RIFT_CLASH => Queue.SummonersRiftClash,
            Camille.Enums.Queue.HOWLING_ABYSS_ARAM_CLASH => Queue.HowlingAbyssAramClash,
            Camille.Enums.Queue.TWISTED_TREELINE_CO_OP_VS_AI_INTERMEDIATE_BOT => Queue.TwistedTreelineCoOpVsAiIntermediateBot,
            Camille.Enums.Queue.TWISTED_TREELINE_CO_OP_VS_AI_INTRO_BOT => Queue.TwistedTreelineCoOpVsAiIntroBot,
            Camille.Enums.Queue.TWISTED_TREELINE_CO_OP_VS_AI_BEGINNER_BOT => Queue.TwistedTreelineCoOpVsAiBeginnerBot,
            Camille.Enums.Queue.SUMMONERS_RIFT_CO_OP_VS_AI_INTRO_BOT => Queue.SummonersRiftCoOpVsAiIntroBot,
            Camille.Enums.Queue.SUMMONERS_RIFT_CO_OP_VS_AI_BEGINNER_BOT => Queue.SummonersRiftCoOpVsAiBeginnerBot,
            Camille.Enums.Queue.SUMMONERS_RIFT_CO_OP_VS_AI_INTERMEDIATE_BOT => Queue.SummonersRiftCoOpVsAiIntermediateBot,
            Camille.Enums.Queue.SUMMONERS_RIFT_ARURF => Queue.SummonersRiftArurf,
            Camille.Enums.Queue.CRYSTAL_SCAR_ASCENSION => Queue.CrystalScarAscension,
            Camille.Enums.Queue.HOWLING_ABYSS_LEGEND_OF_THE_PORO_KING => Queue.HowlingAbyssLegendOfThePoroKing,
            Camille.Enums.Queue.SUMMONERS_RIFT_NEXUS_SIEGE => Queue.SummonersRiftNexusSiege,
            Camille.Enums.Queue.SUMMONERS_RIFT_DOOM_BOTS_VOTING => Queue.SummonersRiftDoomBotsVoting,
            Camille.Enums.Queue.SUMMONERS_RIFT_DOOM_BOTS_STANDARD => Queue.SummonersRiftDoomBotsStandard,
            Camille.Enums.Queue.VALORAN_CITY_PARK_STAR_GUARDIAN_INVASION_NORMAL => Queue.ValoranCityParkStarGuardianInvasionNormal,
            Camille.Enums.Queue.VALORAN_CITY_PARK_STAR_GUARDIAN_INVASION_ONSLAUGHT => Queue.ValoranCityParkStarGuardianInvasionOnslaught,
            Camille.Enums.Queue.OVERCHARGE_PROJECT_HUNTERS => Queue.OverchargeProjectHunters,
            Camille.Enums.Queue.SUMMONERS_RIFT_SNOW_ARURF => Queue.SummonersRiftSnowArurf,
            Camille.Enums.Queue.SUMMONERS_RIFT_ONE_FOR_ALL => Queue.SummonersRiftOneForAll,
            Camille.Enums.Queue.CRASH_SITE_ODYSSEY_EXTRACTION_INTRO => Queue.CrashSiteOdysseyExtractionIntro,
            Camille.Enums.Queue.CRASH_SITE_ODYSSEY_EXTRACTION_CADET => Queue.CrashSiteOdysseyExtractionCadet,
            Camille.Enums.Queue.CRASH_SITE_ODYSSEY_EXTRACTION_CREWMEMBER => Queue.CrashSiteOdysseyExtractionCrewmember,
            Camille.Enums.Queue.CRASH_SITE_ODYSSEY_EXTRACTION_CAPTAIN => Queue.CrashSiteOdysseyExtractionCaptain,
            Camille.Enums.Queue.CRASH_SITE_ODYSSEY_EXTRACTION_ONSLAUGHT => Queue.CrashSiteOdysseyExtractionOnslaught,
            Camille.Enums.Queue.CONVERGENCE_TEAMFIGHT_TACTICS => Queue.ConvergenceTeamfightTactics,
            Camille.Enums.Queue.CONVERGENCE_TEAMFIGHT_TACTICS_1V0 => Queue.ConvergenceTeamfightTactics1V0,
            Camille.Enums.Queue.CONVERGENCE_TEAMFIGHT_TACTICS_2V0 => Queue.ConvergenceTeamfightTactics2V0,
            Camille.Enums.Queue.CONVERGENCE_RANKED_TEAMFIGHT_TACTICS => Queue.ConvergenceRankedTeamfightTactics,
            Camille.Enums.Queue.CONVERGENCE_TEAMFIGHT_TACTICS_TUTORIAL => Queue.ConvergenceTeamfightTacticsTutorial,
            Camille.Enums.Queue.CONVERGENCE_TEAMFIGHT_TACTICS_SIMLUATION => Queue.ConvergenceTeamfightTacticsSimluation,
            Camille.Enums.Queue.CONVERGENCE_RANKED_TEAMFIGHT_TACTICS_HYPER_ROLL_ => Queue.ConvergenceRankedTeamfightTacticsHyperRoll,
            Camille.Enums.Queue.CONVERGENCE_RANKED_TEAMFIGHT_TACTICS_DOUBLE_UP_WORKSHOP__DEPRECATED_1150 => Queue.ConvergenceRankedTeamfightTacticsDoubleUpWorkshopDeprecated1150,
            Camille.Enums.Queue.CONVERGENCE_RANKED_TEAMFIGHT_TACTICS_DOUBLE_UP_WORKSHOP_ => Queue.ConvergenceRankedTeamfightTacticsDoubleUpWorkshop,
            Camille.Enums.Queue.NEXUS_BLITZ_DEPRECATED_1200 => Queue.NexusBlitzDeprecated1200,
            Camille.Enums.Queue.NEXUS_BLITZ => Queue.NexusBlitz,
            Camille.Enums.Queue.SUMMONERS_RIFT_ULTIMATE_SPELLBOOK => Queue.SummonersRiftUltimateSpellbook,
            Camille.Enums.Queue.ARENA_2V2V2V2_CHERRY_ => Queue.Arena2V2V2V2Cherry,
            Camille.Enums.Queue.SUMMONERS_RIFT_PICK_URF => Queue.SummonersRiftPickUrf,
            Camille.Enums.Queue.SUMMONERS_RIFT_TUTORIAL_1 => Queue.SummonersRiftTutorial1,
            Camille.Enums.Queue.SUMMONERS_RIFT_TUTORIAL_2 => Queue.SummonersRiftTutorial2,
            Camille.Enums.Queue.SUMMONERS_RIFT_TUTORIAL_3 => Queue.SummonersRiftTutorial3,
            _ => throw new ArgumentOutOfRangeException(nameof(queue), queue, null)
        };
}