namespace LeagueOfStats.Domain.Matches;

public enum GameMode
{
    Aram,
    Arsr,
    Arena,
    Ascension,
    Assassinate,
    Classic,
    DarkStar,
    DoomBots,
    FirstBlood,
    GameModeX,
    KingPoro,
    NexusBlitz,
    Odin,
    Odyssey,
    OneForAll,
    PracticeTool,
    Project,
    Siege,
    StarGuardian,
    Tutorial,
    TutorialModule1,
    TutorialModule2,
    TutorialModule3,
    Ultbook,
    Urf,
}